### ISSUE TITLE
Compilation of Trusted Application error

### ISSUE THREAD

**Issue by AymericGenet** [vascoguita/optee_gmp#1]
Hello,

First of all, thank you for making this project available; this has definitely made things way easier for a newbie in the domain of OP-TEE like me 😊

Speaking of which, I need to use GMP in a Trusted Application and had a bit of troubles using the resulting compiled library. I was wondering if you could lend me a hand?

I followed the instructions in the README (whose entire output can be found here: https://pastebin.com/Vawv57NU). However, when I try to compile a Trusted Application using a small example which involves GMP (see below), I get the following error message:

```
aymeric@pegasus:/mnt/c/Projects/FENTEC/example/TA/src$ CROSS_COMPILE=$CROSS_COMPILE TA_DEV_KIT_DIR=$TA_DEV_KIT_DIR make
Binary of TA edda258d-6d7c-4fb3-95c0-544a0a9189d9
Using TA_DEV_KIT_DIR=/mnt/c/Projects/FENTEC/optee/build.mx8mmevk/export-ta_arm64
  CC      ta_entry.o
  CC      user_ta_header.o
  CPP     ta.lds
  LD      edda258d-6d7c-4fb3-95c0-544a0a9189d9.elf
aarch64-linux-gnu-ld.bfd: ./ta_entry.o: in function `test':
/mnt/c/Projects/FENTEC/example/TA/src/ta_entry.c:17: undefined reference to `__gmp_printf'
aarch64-linux-gnu-ld.bfd: /mnt/c/Projects/FENTEC/optee/build.mx8mmevk/export-ta_arm64/lib/libgmp.a(lt41-set_str.o): in function `__gmpz_set_str':
/mnt/c/Projects/FENTEC/optee_gmp/gmp-6.2.0/mpz/set_str.c:68: undefined reference to `isspace'
aarch64-linux-gnu-ld.bfd: /mnt/c/Projects/FENTEC/optee_gmp/gmp-6.2.0/mpz/set_str.c:103: undefined reference to `isspace'
aarch64-linux-gnu-ld.bfd: /mnt/c/Projects/FENTEC/optee_gmp/gmp-6.2.0/mpz/set_str.c:120: undefined reference to `isspace'
make: *** [/mnt/c/Projects/FENTEC/optee/build.mx8mmevk/export-ta_arm64/mk/link.mk:48: edda258d-6d7c-4fb3-95c0-544a0a9189d9.elf] Error 1
```

The application in question (`ta_entry.c`):

```C
#include <tee_ta_api.h>
#include <stdio.h>
#include <gmp.h>

TEE_Result TA_CreateEntryPoint(void)
{
    return TEE_SUCCESS;
}

void TA_DestroyEntryPoint(void) { }

static void test(void)
{
    mpz_t a;
    mpz_init(a);
    mpz_set_str(a, "42", 10);
    gmp_printf("%Zd\n",a);
    mpz_clear(a);
}

TEE_Result TA_OpenSessionEntryPoint(uint32_t ptype,
                                    TEE_Param param[TEE_NUM_PARAMS],
                                    void** session_id_ptr)
{
    (void)(ptype);
    (void)(param);
    (void)(session_id_ptr);

    return TEE_SUCCESS;
}

void TA_CloseSessionEntryPoint(void* sess_ptr)
{
    (void)(sess_ptr);
}

TEE_Result TA_InvokeCommandEntryPoint(void* session_id,
                                      uint32_t command_id,
                                      uint32_t parameters_type,
                                      TEE_Param parameters[TEE_NUM_PARAMS])
{
    TEE_Result result = 0;
    (void) (session_id);

    test();
    result = TEE_SUCCESS;

    return result;
}
```

And the `sub.mk`:

```make
global-incdirs-y += ../include
srcs-y += ta_entry.c
libnames += gmp
cflags += -D_GNU_SOURCE
```

For reference, I am on Windows 10 and use the Ubuntu on WSL. The version of OP-TEE was flavored for the NXP i.MX8M built directly from the latest version of the Yocto Project.

Best regards,
Aymeric

**Comment by vascoguita** [comment]
Hello Aymeric,

Thanks for the interest and for reporting this problem. I will take a look and try to solve it.
This library was originally ported to support the [port of the PBC library for OP-TEE](https://github.com/vascoguita/optee_pbc). Other use cases were not tested and further work might be required as one tries to use it in other projects.

If you manage to solve this problem or other (probable) future problems please share the solution by making a pull request :)

Best regards,
Vasco

**Comment by AymericGenet** [comment]
Hi Vasco,

Thank you for your answer! I'm currently investigating the problem and so far, I've tried the following:

1) From https://github.com/OP-TEE/optee_os/issues/1255, the proper way to add a library is (1) to add `LDFLAGS = -static` in the Makefile and (2) to add the following lines the `sub.mk` (a few were missing in my case):
```
libnames += gmp
libdeps += $(ta-dev-kit-dir)/lib/libgmp.a
libdeps += $(ta-dev-kit-dir)/lib/libgmp.la
```
2) From https://github.com/OP-TEE/optee_os/issues/1032, make sure `-lgmp` is called *after* `-lutils` (or, simply at the end). By adding the above line in `sub.mk` the library should be called after. Still, one can always make sure by directly modifying `$TA_DEV_KIT_DIR/mk/ta_dev_kit.mk` under the `libnames`and `libdeps` entries (lines 54-58 in my case).
3) Also from https://github.com/OP-TEE/optee_os/issues/1255, jbech-linaro explains that:

> [...] you will get into an issue we've seen a couple of times and that is that the library itself might use "undefined" functions. Remember that OP-TEE doesn't contain a full "stdlib". We've just picked and/or implemented the functions that has been needed so far. If this is the kind of linker errors you get, then I believe the only way to get any further is to start implementing (or pick .. newlib?) the missing functions.

This was also specifically explained for the libgmp case in https://github.com/OP-TEE/optee_os/issues/1003 where jforissier states that:

> You get an undefined reference to vprintf because libutils.a (which is more or less our C library for TAs) does not provide this function. The primary API that TAs are supposed to use it the GobalPlatform TEE Core Internal API. That is why we are not trying to provide a complete C library in libutils.a, although we do provide some well-known functions (you can see which ones with $(CROSS_COMPILE)-nm libutils.a | grep " T "). They are provided mainly to help implement the GP API.

I'm still scratching my head as to how take these pieces of advice into account. The undefined `isspace(char)` shouldn't be that hard to re-implement, but I'm afraid that going down this road will require the re-implementation of many many functions, so I'm still hoping for a solution that covers every missing definition.

Anyway, thanks for looking at this, I'll make sure to keep this issue updated as I make new discoveries.

Best regards,
Aymeric

**Comment by vascoguita** [comment]
1. & 2. My sugestion is to install the library according to the README:

```
make CROSS_COMPILE=<path/to/aarch64-linux-gnu-> TA_DEV_KIT_DIR <optee_os>/out/arm/export-ta_arm64 --no-builtin-variables
make install
```
And link it to your TA by adding this to the Makefile of the TA:
`LDADD += $(TA_DEV_KIT_DIR)/lib/libgmp.a`

Sure, there are other ways but with this one you just edit files of your project and leave the OP-TEE OS untouched :).

3. I think the solution here is indeed to re-implement the `isspace(char)` function. But I think we have to find a workaround for this line of your code: `gmp_printf("%Zd\n",a);` OP-TEE doesn't provide the standard streams (stdin, stdout and stderr). Hence you might want to use `gmp_snprintf(char *, size_t, const char *, ...)` and pass the resulting string to one of the log functions provided: `IMSG(...)`, `DMSG(...)` , `EMSG(...)`. This is the  closest to a printf you will get without having to pass the result to your client on the REE for him to print.

Note: Don't forget to increase the log level when compiling OP-TEE, otherwise the output of these functions won't be printed.

**Comment by AymericGenet** [comment]
Alright, I think I'm onto something.

You're right, I needed to find a workaround for `gmp_printf`. With reconsideration, I realized that I didn't actually need to print anything; only to perform multiple precision computations. Moreover, even the `mpz_set_str` is unrealistic as I intend to transmit data to the TA through a buffer of bytes.

As a consequence, I modified the code to create a small working example that
1) imports bytes from the input parameters,
2) performs GMP operations with said input, and
3) exports result into the output parameters.

The result is below and the code finally compiles (**DISCLAIMER:** the code wasn't test yet):

```C
#include <tee_ta_api.h>
#include <gmp.h>

/* GMP basic import/export example */
#define MPZ_WORDS_MAX 32
#define MPZ_WORDS_ORDER 1 /* Most significant order first */
#define MPZ_WORDS_ENDIANNESS 0 /* Use host endianness */
#define MPZ_NAILS 0 /* Use full words */

TEE_Result TA_CreateEntryPoint(void)
{
    return TEE_SUCCESS;
}

void TA_DestroyEntryPoint(void)
{
    return;
}

static TEE_Result TA_ComputeGMP(uint32_t param_types,
                                TEE_Param params[4])
{
    mpz_t input, output;
    const uint32_t exp_param_types =
        TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT, /* params[0]: input  */
                TEE_PARAM_TYPE_MEMREF_OUTPUT,        /* params[1]: output */
                TEE_PARAM_TYPE_NONE,                 /* params[2]: (none) */
                TEE_PARAM_TYPE_NONE);                /* params[3]: (none) */
    char *data_inp = 0, *data_out = 0;
    size_t data_inp_sz = 0, data_out_sz = 0;

    /* Handles unexpected parameters combination */
    if (param_types != exp_param_types)
    {
        return TEE_ERROR_BAD_PARAMETERS;
    }

    /* Handles input buffer */
    data_inp = (char *)params[0].memref.buffer;
    data_inp_sz = params[0].memref.size;
    if (data_inp_sz > MPZ_WORDS_MAX)
    {
        /* Input buffer unexpectedly large */
        return TEE_ERROR_BAD_PARAMETERS;
    }

    /* Imports data_inp in mpz_t */
    mpz_init(input);
    mpz_import(input,
               data_inp_sz,
               MPZ_WORDS_ORDER,
               sizeof(data_inp[0]),
               MPZ_WORDS_ENDIANNESS,
               MPZ_NAILS,
               data_inp);

    /* <insert your computations with mpz_t here> */
    mpz_init_set(output, input);

    /* Handles output bufer */
    data_out = (char *)params[1].memref.buffer;
    data_out_sz = params[1].memref.size;
    if (data_out_sz < mpz_sizeinbase(output, (1 << 8))) /* size in bytes */
    {
        /* Output buffer too short */
        return TEE_ERROR_BAD_PARAMETERS;
    }

    /* Exports mpz_t in data_out */
    mpz_export(data_out,
               &data_out_sz,
               MPZ_WORDS_ORDER,
               sizeof(data_inp[0]),
               MPZ_WORDS_ENDIANNESS,
               MPZ_NAILS,
               output);

    /* Cleans up */
    mpz_clears(input, output);

    return TEE_SUCCESS;
}

TEE_Result TA_OpenSessionEntryPoint(uint32_t param_types,
                                    TEE_Param params[TEE_NUM_PARAMS],
                                    void** session_id_ptr)
{
    (void)(param_types);
    (void)(params);
    (void)(session_id_ptr);

    return TEE_SUCCESS;
}

void TA_CloseSessionEntryPoint(void* sess_ptr)
{
    (void)(sess_ptr);
}

TEE_Result TA_InvokeCommandEntryPoint(void* session_id,
                                      uint32_t command_id,
                                      uint32_t param_types,
                                      TEE_Param params[TEE_NUM_PARAMS])
{
    (void) (session_id);
    (void) (command_id);

    return TA_ComputeGMP(param_types, params);
}
```

The main takeaway from this is to really consider the actual operations needed to carry out your task with GMP and not to expect every function from GMP to work as in a normal environment, especially in the context of OP-TEE. Still, re-implementation of missing features might be considered.

I think that a small list of all the GMP features that work with the current libutils would be a valuable piece of information for your project, I'll see if I can provide you with this.

Once again, many thanks for your help, it really helped me through my development. I'm not done with my project yet, but I'm happy to have made such a big step forward! 😃

Best regards,
Aymeric

**Comment by vascoguita** [comment]
Hello Aymeric,

I'm glad you made progress.
You are right, it would be good to provide a list of the working functions of this library.
I will start by adding the ones I used and then we can add yours to make the list more complete.

Thanks for sharing your experience using the library and for your advises. :slightly_smiling_face:

Greetings,
Vasco
